INSERT INTO jobs (
    title,
    company,
    location,
    description,
    employment_type,
    experience_level,
    remote_type,
    salary_min,
    salary_max,
    posted_at,
    source,
    source_url
)
VALUES
(
    'Junior Java Backend Developer',
    'TechNova',
    'Istanbul',
    'We are looking for a junior Java developer with Spring Boot, PostgreSQL and Git experience.',
    'FULL_TIME',
    'JUNIOR',
    'HYBRID',
    35000,
    50000,
    '2026-08-01 10:00:00',
    'SAMPLE',
    'https://example.com/jobs/1'
),
(
    'Backend Developer',
    'CloudWorks',
    'Ankara',
    'Experience with Java, Spring Boot, PostgreSQL, Docker and REST APIs is required.',
    'FULL_TIME',
    'MID',
    'REMOTE',
    50000,
    75000,
    '2026-08-03 10:00:00',
    'SAMPLE',
    'https://example.com/jobs/2'
),
(
    'Frontend Developer',
    'WebLabs',
    'Istanbul',
    'Looking for a React developer with TypeScript, HTML, CSS and Git experience.',
    'FULL_TIME',
    'JUNIOR',
    'HYBRID',
    30000,
    45000,
    '2026-08-05 10:00:00',
    'SAMPLE',
    'https://example.com/jobs/3'
),
(
    'Full Stack Developer',
    'SoftHouse',
    'Izmir',
    'Experience with Java, Spring Boot, React, PostgreSQL and Docker.',
    'FULL_TIME',
    'MID',
    'ONSITE',
    45000,
    70000,
    '2026-08-07 10:00:00',
    'SAMPLE',
    'https://example.com/jobs/4'
),
(
    'Python Developer',
    'DataTech',
    'Istanbul',
    'Python development experience with FastAPI, PostgreSQL and Docker.',
    'FULL_TIME',
    'JUNIOR',
    'REMOTE',
    35000,
    55000,
    '2026-08-09 10:00:00',
    'SAMPLE',
    'https://example.com/jobs/5'
);